[package]
name = "backend-migration"
version = "0.1.0"
edition.workspace = true

[lib]
name = "backend_migration"
path = "src/lib.rs"

[[bin]]
name = "backend-migration"
path = "src/main.rs"

[dependencies]
async-std = { version = "1", features = ["attributes", "tokio1"] }
sleep-companion-backend = { path = "../backend" }
sea-orm-migration = { version = "1", features = ["runtime-tokio-rustls", "sqlx-postgres"] }
